version: '2.4'

services:
  hat-frontend:
    container_name: hat-frontend
    build: ./../hat-frontend
    image: hat-frontend:latest
    mem_limit: 256m
    mem_reservation: 128m
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  hat-api-gateway:
    container_name: hat-api-gateway
    build: ./../hat-api-gateway
    image: hat-api-gateway:latest
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - 9002:9002
    environment:
      APP_HOST: 172.17.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    depends_on:
      - hat-user-service
  hat-user-service:
    container_name: hat-user-service
    build: ./../hat-user-back
    image: hat-user:latest
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - 9001:9001
    environment:
      APP_HOST: 172.17.0.1
      DB_PORT: 5401
      DB_USER: hat_user
      DB_PASSWORD: test1234
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    depends_on:
      - "hat-db"
  hat-game-service:
    container_name: hat-game-service
    build: ./../hat-game-back
    image: hat-game:latest
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - 9000:9000
    environment:
      APP_HOST: 172.17.0.1
      DB_PORT: 5401
      DB_USER: hat_user
      DB_PASSWORD: test1234
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    depends_on:
      - "hat-db"
  hat-db:
    image: 'postgres:15'
    container_name: hat-db
    ports:
      - 5401:5432
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - hat_user_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hat_user
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  hat-mq:
    image: 'bitnami/rabbitmq:3.11.6'
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_USERNAME=hat_user
      - RABBITMQ_PASSWORD=test1234
volumes:
  hat_user_db_data:
